meta_product_name: "GN Map"
meta_title: "GN Map - Step into the Story, LARP Your Way"
meta_description: "GN Map is an immersive website where you can book, or create LARP events, invite your friends, and lead the way to LARP events all over the world! "
meta_image: "Logo_GN.png" # should exist in `app/assets/images/`
